[package]
name = "aloroid/itempluginv3"
version = "0.1.1"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
CubeCat = "aloroid/cubecat@0.1.1"
Fusion = "elttob/fusion@0.2.0"